apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-data
  namespace: vertica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2  # Must match the cluster's available StorageClass

